# Generated by Django 3.2.3 on 2021-08-31 21:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie_booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='numberOfSeats',
            new_name='number_of_seats',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='timeStamp',
        ),
        migrations.AddField(
            model_name='booking',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
