version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo "Building"
  build:
    commands:
      - echo "Running all unit tests"
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'